# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9404f7971ea56b45f17c1f4c0fdf7efa3b6a27249b5857ec8d8fb99055205622465783b6029bf528e5088f0ee09b021caaf9f1f9aeddcd503761feb66bf51c7

test:
  secret_key_base: 36a8e11b5a5895dbba2c4432f25c142143deab0eb39d91c47d03754a9913d4741090819a0047e70b3f75fa047abd41e65437840b548f8702a94e70693b4bf480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
